fix: Fix opencv warning.

diff --git a/Dockerfile.deploy b/Dockerfile.deploy
--- a/Dockerfile.deploy
+++ b/Dockerfile.deploy
@@ -86,8 +86,8 @@ RUN wget --quiet --show-progress --progress=bar:force:noscroll --no-check-certif
 # Description: Install OpenCV 4.5.0 with CUDA
 # Size: 477MB
 #
-RUN apt-get purge -y '*opencv*' || echo "previous OpenCV installation not found" && \
-    mkdir opencv && \
+#RUN apt-get purge -y '*opencv*' || echo "previous OpenCV installation not found" && \
+RUN mkdir opencv && \
     cd opencv && \
     wget --quiet --show-progress --progress=bar:force:noscroll --no-check-certificate https://nvidia.box.com/shared/static/5v89u6g5rb62fpz4lh0rz531ajo2t5ef.gz -O OpenCV-4.5.0-aarch64.tar.gz && \
     tar -xzvf OpenCV-4.5.0-aarch64.tar.gz && \
